export const heading1 = [
  { label: "id", name: "ID", sort: true },
  { label: "name", name: "Name", sort: false,hasInput:true, },
  { label: "country", name: "Country", sort: true,hasInput:true, },
  { label: "skills", name: "Skills", sort: true,hasInput:true, },
  { label: "profiency", name: "Profiency", sort: true },
];
export const heading2 = [
  { label: "id", name: "ID", sort: true },
  { label: "first_name", name: "First Name", sort: false ,hasInput:true,},
  { label: "last_name", name: "Last Name", sort: false,hasInput:true, },
  { label: "email", name: "Email", sort: false,hasInput:true, },
  { label: "product_name", name: "Product Name", sort: false,hasInput:true, },
  { label: "quantity", name: "Quantity", sort: true },
  { label: "price", name: "Price", sort: true },
  { label: "total", name: "Total", sort: true },
];

export const data1 = [
  {
    id: 1,
    name: "Elberta Facher",
    country: "Brazil",
    skills: "UC4",
    profiency: 28,
  },
  {
    id: 2,
    name: "Laina Raynor",
    country: "Portugal",
    skills: "MRIS",
    profiency: 45,
  },
  {
    id: 3,
    name: "Jim Toon",
    country: "Portugal",
    skills: "MSS",
    profiency: 27,
  },
  {
    id: 4,
    name: "Mechelle Leward",
    country: "Tanzania",
    skills: "Japanese Language Proficiency Test",
    profiency: 31,
  },
  {
    id: 5,
    name: "Hi Figge",
    country: "Indonesia",
    skills: "Urban Planning",
    profiency: 17,
  },
  {
    id: 6,
    name: "Marsh Springell",
    country: "Philippines",
    skills: "Pro Tools",
    profiency: 31,
  },
  {
    id: 7,
    name: "Saundra Broadhurst",
    country: "Philippines",
    skills: "DLS",
    profiency: 61,
  },
  {
    id: 8,
    name: "Jacqueline Greenrod",
    country: "Russia",
    skills: "Cash Flow",
    profiency: 70,
  },
  {
    id: 9,
    name: "Noelle Foster",
    country: "France",
    skills: "iGrafx",
    profiency: 46,
  },
  {
    id: 10,
    name: "Rosamund Nevett",
    country: "Brazil",
    skills: "Dubbing",
    profiency: 49,
  },
  {
    id: 11,
    name: "Bealle Cuncliffe",
    country: "China",
    skills: "Graphics",
    profiency: 76,
  },
  {
    id: 12,
    name: "Lawry Cliss",
    country: "China",
    skills: "IP",
    profiency: 75,
  },
  {
    id: 13,
    name: "Kassandra Harlow",
    country: "Ukraine",
    skills: "Whitewater Kayaking",
    profiency: 2,
  },
  {
    id: 14,
    name: "Sheila-kathryn Silver",
    country: "Colombia",
    skills: "Gastroenterology",
    profiency: 99,
  },
  {
    id: 15,
    name: "Dahlia Singers",
    country: "China",
    skills: "Multi-color Flow Cytometry",
    profiency: 81,
  },
  {
    id: 16,
    name: "Bryn McArthur",
    country: "Czech Republic",
    skills: "Orchestral Music",
    profiency: 17,
  },
  {
    id: 17,
    name: "Bibbie Yorath",
    country: "Trinidad and Tobago",
    skills: "TPE",
    profiency: 27,
  },
  {
    id: 18,
    name: "Demetra Achurch",
    country: "Tunisia",
    skills: "PV Design",
    profiency: 91,
  },
  {
    id: 19,
    name: "Winni Passingham",
    country: "Greece",
    skills: "RNAi",
    profiency: 95,
  },
  {
    id: 20,
    name: "Maison Sharplin",
    country: "China",
    skills: "FX Trading",
    profiency: 48,
  },
];

export const data2 = [
  {
    id: 1,
    first_name: "Cammi",
    last_name: "Childs",
    email: "cchilds0@yahoo.co.jp",
    product_name: "Bread - Mini Hamburger Bun",
    quantity: 29,
    price: 9.9,
    total: 287.1,
  },
  {
    id: 2,
    first_name: "Kermy",
    last_name: "Borborough",
    email: "kborborough1@discuz.net",
    product_name: "Rabbit - Frozen",
    quantity: 27,
    price: 47.5,
    total: 1282.5,
  },
  {
    id: 3,
    first_name: "Donelle",
    last_name: "Kiley",
    email: "dkiley2@whitehouse.gov",
    product_name: "Gatorade - Lemon Lime",
    quantity: 14,
    price: 38.7,
    total: 541.8,
  },
  {
    id: 4,
    first_name: "Eolande",
    last_name: "Napier",
    email: "enapier3@cafepress.com",
    product_name: "Ice Cream - Vanilla",
    quantity: 19,
    price: 45.8,
    total: 870.2,
  },
  {
    id: 5,
    first_name: "Emmery",
    last_name: "Liversage",
    email: "eliversage4@so-net.ne.jp",
    product_name: "Squash - Pepper",
    quantity: 22,
    price: 10.4,
    total: 228.8,
  },
  {
    id: 6,
    first_name: "Dita",
    last_name: "Witcombe",
    email: "dwitcombe5@msu.edu",
    product_name: "Pea - Snow",
    quantity: 54,
    price: 9.1,
    total: 491.4,
  },
  {
    id: 7,
    first_name: "Jorge",
    last_name: "Broschek",
    email: "jbroschek6@army.mil",
    product_name: "Soup - Knorr, Chicken Noodle",
    quantity: 11,
    price: 55.6,
    total: 611.6,
  },
  {
    id: 8,
    first_name: "Bibby",
    last_name: "Haddacks",
    email: "bhaddacks7@printfriendly.com",
    product_name: "Vinegar - Balsamic",
    quantity: 12,
    price: 20.6,
    total: 247.2,
  },
  {
    id: 9,
    first_name: "Sigvard",
    last_name: "Stuehmeyer",
    email: "sstuehmeyer8@friendfeed.com",
    product_name: "Glass - Wine, Plastic, Clear 5 Oz",
    quantity: 49,
    price: 18.9,
    total: 926.1,
  },
  {
    id: 10,
    first_name: "Shannon",
    last_name: "Blenkinsopp",
    email: "sblenkinsopp9@utexas.edu",
    product_name: "Wine - Marlbourough Sauv Blanc",
    quantity: 14,
    price: 25.5,
    total: 357.0,
  },
  {
    id: 11,
    first_name: "Gaspar",
    last_name: "Gagie",
    email: "ggagiea@soup.io",
    product_name: "Puree - Blackcurrant",
    quantity: 12,
    price: 27.8,
    total: 333.6,
  },
  {
    id: 12,
    first_name: "Anya",
    last_name: "Crangle",
    email: "acrangleb@techcrunch.com",
    product_name: "Tray - 12in Rnd Blk",
    quantity: 1,
    price: 26.4,
    total: 26.4,
  },
  {
    id: 13,
    first_name: "Con",
    last_name: "Balderston",
    email: "cbalderstonc@sciencedirect.com",
    product_name: "Artichoke - Bottom, Canned",
    quantity: 20,
    price: 51.3,
    total: 1026.0,
  },
  {
    id: 14,
    first_name: "Erasmus",
    last_name: "Endle",
    email: "eendled@exblog.jp",
    product_name: "Spice - Greek 1 Step",
    quantity: 52,
    price: 2.2,
    total: 114.4,
  },
  {
    id: 15,
    first_name: "Denise",
    last_name: "Edwardes",
    email: "dedwardese@slashdot.org",
    product_name: "Pasta - Canelloni",
    quantity: 4,
    price: 39.5,
    total: 158.0,
  },
  {
    id: 16,
    first_name: "Chrissie",
    last_name: "Rocca",
    email: "croccaf@seattletimes.com",
    product_name: "Rhubarb",
    quantity: 26,
    price: 27.8,
    total: 722.8,
  },
  {
    id: 17,
    first_name: "Evey",
    last_name: "Facchini",
    email: "efacchinig@behance.net",
    product_name: "Zucchini - Yellow",
    quantity: 29,
    price: 39.6,
    total: 1148.4,
  },
  {
    id: 18,
    first_name: "Bradney",
    last_name: "Rosindill",
    email: "brosindillh@imageshack.us",
    product_name: "Mix - Cappucino Cocktail",
    quantity: 17,
    price: 15.0,
    total: 255.0,
  },
  {
    id: 19,
    first_name: "Caresse",
    last_name: "Brou",
    email: "cbroui@bing.com",
    product_name: "Fish - Scallops, Cold Smoked",
    quantity: 8,
    price: 35.5,
    total: 284.0,
  },
  {
    id: 20,
    first_name: "Nina",
    last_name: "Twallin",
    email: "ntwallinj@istockphoto.com",
    product_name: "Tea - Herbal Orange Spice",
    quantity: 24,
    price: 23.3,
    total: 559.2,
  },
  {
    id: 21,
    first_name: "Carr",
    last_name: "Blackway",
    email: "cblackwayk@wunderground.com",
    product_name: "Turkey - Oven Roast Breast",
    quantity: 2,
    price: 6.5,
    total: 13.0,
  },
  {
    id: 22,
    first_name: "Gerhard",
    last_name: "Ferrige",
    email: "gferrigel@go.com",
    product_name: "Nori Sea Weed - Gold Label",
    quantity: 44,
    price: 34.5,
    total: 1518.0,
  },
  {
    id: 23,
    first_name: "Elyn",
    last_name: "Allmark",
    email: "eallmarkm@wp.com",
    product_name: "Pork - Bones",
    quantity: 5,
    price: 14.1,
    total: 70.5,
  },
  {
    id: 24,
    first_name: "Lolita",
    last_name: "Bretelle",
    email: "lbretellen@wix.com",
    product_name: "Sloe Gin - Mcguinness",
    quantity: 47,
    price: 12.4,
    total: 582.8,
  },
  {
    id: 25,
    first_name: "Yorker",
    last_name: "Davidman",
    email: "ydavidmano@examiner.com",
    product_name: "Lamb Tenderloin Nz Fr",
    quantity: 56,
    price: 30.8,
    total: 1724.8,
  },
  {
    id: 26,
    first_name: "Melli",
    last_name: "Sola",
    email: "msolap@networksolutions.com",
    product_name: "Artichokes - Knobless, White",
    quantity: 32,
    price: 39.3,
    total: 1257.6,
  },
  {
    id: 27,
    first_name: "Julissa",
    last_name: "Pree",
    email: "jpreeq@xing.com",
    product_name: "Wine - Lamancha Do Crianza",
    quantity: 10,
    price: 54.8,
    total: 548.0,
  },
  {
    id: 28,
    first_name: "Marja",
    last_name: "Simpkin",
    email: "msimpkinr@etsy.com",
    product_name: "Amaretto",
    quantity: 46,
    price: 3.2,
    total: 147.2,
  },
  {
    id: 29,
    first_name: "Rozalie",
    last_name: "Shropshire",
    email: "rshropshires@homestead.com",
    product_name: "Lettuce - California Mix",
    quantity: 8,
    price: 52.0,
    total: 416.0,
  },
  {
    id: 30,
    first_name: "Lizzie",
    last_name: "Spyvye",
    email: "lspyvyet@amazonaws.com",
    product_name: "Water - Green Tea Refresher",
    quantity: 46,
    price: 50.9,
    total: 2341.4,
  },
  {
    id: 31,
    first_name: "Wallie",
    last_name: "Hunnicutt",
    email: "whunnicuttu@sitemeter.com",
    product_name: "Bread Country Roll",
    quantity: 51,
    price: 22.0,
    total: 1122.0,
  },
  {
    id: 32,
    first_name: "Natala",
    last_name: "Cashford",
    email: "ncashfordv@google.com.br",
    product_name: "Trout - Rainbow, Fresh",
    quantity: 23,
    price: 53.7,
    total: 1235.1,
  },
  {
    id: 33,
    first_name: "Dotti",
    last_name: "Perroni",
    email: "dperroniw@nydailynews.com",
    product_name: "Icecream Cone - Areo Chocolate",
    quantity: 31,
    price: 6.9,
    total: 213.9,
  },
  {
    id: 34,
    first_name: "Tracie",
    last_name: "Warrilow",
    email: "twarrilowx@merriam-webster.com",
    product_name: "Veal - Sweetbread",
    quantity: 43,
    price: 46.5,
    total: 1999.5,
  },
  {
    id: 35,
    first_name: "Juanita",
    last_name: "Abrashkin",
    email: "jabrashkiny@hubpages.com",
    product_name: "Olives - Green, Pitted",
    quantity: 40,
    price: 34.8,
    total: 1392.0,
  },
];
